# AUTOGENERATED FILE
FROM resin/$device-buildpack-deps:latest

ENV NODE_VERSION $binary_version

RUN curl -SL "$binary_url" -o $binary_name \
	&& echo "$binary_hash" | sha256sum -c - \
	&& tar -xzf $binary_name -C /usr/local --strip-components=1 \
	&& rm $binary_name \
	&& npm config set unsafe-perm true -g --unsafe-perm \
	&& rm -rf /tmp/*

CMD ["echo","'No CMD command was set in Dockerfile! Details about CMD command could be found in Dockerfile Guide section in our Docs. Here's the link: http://docs.resin.io/#/pages/using/dockerfile.md"]
